repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length", "79"]
      - id: black
        name: black (.pyi)
        args: ["--line-length", "79"]
        types: [pyi]
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        language: system
        files: \.(c|h|cpp|hpp|proto|java)$
        entry: clang-format -i
  - repo: https://github.com/eschulte/lisp-format
    rev: master
    hooks:
      - id: lisp-format
        name: lisp-format
        args: [-style=file]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--chars"," \t"]
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: mixed-line-ending
  - repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
    rev: v0.6.2
    hooks:
      - id: cmake-format
        exclude: build
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.19
    hooks:
      - id: isort
        files: \.py$
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
